// react-ttt/src/Board.jsx
import React from 'react'
import {Square} from './Square';

export class Board extends React.Component {
  renderSquare(i) {
    return (
      <Square
        value={this.props.squares[i]}
        onClick={() => this.props.onClick(i)}
      />
    );
  }

  render() {
    return (
      <div>
        <div className="board-row">
          {this.renderSquare(0)}
          {this.renderSquare(1)}
          {this.renderSquare(2)}
        </div>
        <div className="board-row">
          {this.renderSquare(3)}
          {this.renderSquare(4)}
          {this.renderSquare(5)}
        </div>
        <div className="board-row">
          {this.renderSquare(6)}
          {this.renderSquare(7)}
          {this.renderSquare(8)}
        </div>
      </div>
    );
  }
}

// svelte/src/Board.svelte
<script>
  import Square from './Square.svelte';
  export let squares;
  export let handleClick;
</script>
<style>
  .board-row:after {
    clear: both;
    content: "";
    display: table;
  }
</style>
<div class="game-board">
  <div class="board-row">
    {#each [0, 1, 2] as i}
      <Square value={squares[i]} handleClick={() => handleClick(i)} />
    {/each}
  </div>
  <div class="board-row">
    {#each [3, 4, 5] as i}
      <Square value={squares[i]} handleClick={() => handleClick(i)} />
    {/each}
  </div>
  <div class="board-row">
    {#each [6, 7, 8] as i}
      <Square value={squares[i]} handleClick={() => handleClick(i)} />
    {/each}
  </div>
</div>
