// react-tic-tac-toe/src/Game.jsx
import React from 'react';
import './Game.css';
import { calculateWinner } from './utils';
import { Board } from './Board';

class Game extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
      history: [
        {
          squares: Array(9).fill(null)
        }
      ],
      stepNumber: 0,
      xIsNext: true
    };
  }

  handleClick(i) {
    const history = this.state.history.slice(0, this.state.stepNumber + 1);
    const current = history[history.length - 1];
    const squares = current.squares.slice();
    if (calculateWinner(squares) || squares[i]) {
      return;
    }
    squares[i] = this.state.xIsNext ? "X" : "O";
    this.setState({
      history: history.concat([
        {
          squares: squares
        }
      ]),
      stepNumber: history.length,
      xIsNext: !this.state.xIsNext
    });
  }

  jumpTo(step) {
    this.setState({
      stepNumber: step,
      xIsNext: (step % 2) === 0
    });
  }

  render() {
    const history = this.state.history;
    const current = history[this.state.stepNumber];
    const winner = calculateWinner(current.squares);

    const moves = history.map((step, move) => {
      const desc = move ?
        'Go to move #' + move :
        'Go to game start';
      return (
        <li key={move}>
          <button onClick={() => this.jumpTo(move)}>{desc}</button>
        </li>
      );
    });

    let status;
    if (winner) {
      status = "Winner: " + winner;
    } else {
      status = "Next player: " + (this.state.xIsNext ? "X" : "O");
    }

    return (
      <div className="game">
        <div className="game-board">
          <Board
            squares={current.squares}
            onClick={i => this.handleClick(i)}
          />
        </div>
        <div className="game-info">
          <div>{status}</div>
          <ol>{moves}</ol>
        </div>
      </div>
    );
  }
}

export default Game;

// svelte/src/Game.svelte
<script>
  import Board from './Board.svelte';
  import { calculateWinner } from './utils';

  let history = [{
    squares: Array(9).fill(null)
  }];
  let xIsNext = true;

  let status, winner;
  $: current = history[history.length - 1];
  $: length = history.length;
  $: winner = calculateWinner(current.squares);
  $: if (winner) {
    status = `Winner: ${winner}`;
  } else {
    status = 'Next player: ' + (xIsNext ? 'X' : 'O');
  }

  function handleClick(i) {
    if (current[i] || winner) {
      return;
    }
    let squares = current.squares.slice();
    squares[i] = xIsNext ? 'X' : 'O';
    // history.push doesn't yet work ;(
    history[history.length] = { squares };
    xIsNext = !xIsNext;
  }
</script>
<style>
  .game-logo {
    display: flex;
    margin: 0 auto 20px;
    width: 350px;
    font-size: 30px;
    line-height: 50px;
  }
  .game-logo img {
    width: 50px;
    height: 50px;
    margin-right: 10px;
  }
	.game {
	  margin: auto;
	  width: 350px;
    display: flex;
    flex-direction: row;
  }
  .game-info {
    margin-left: 20px;
  }
</style>
<div class="game-logo">
  <img src="https://image.flaticon.com/icons/svg/1527/1527318.svg" alt="Tic Tac Toe"> Tic Tac Toe
</div>
<div class="game">
  <Board squares={current.squares} handleClick={handleClick} />
  <div class="game-info">
    <div>{status}</div>
    <ol><!-- TODO --></ol>
  </div>
</div>
